name: wedding-app
services:
  invoice-app:
    container_name: invoice-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8012"
    environment:
      CONSUL_HTTP_URL: ${CONSUL_HTTP_URL}
      CONSUL_HTTP_KEY: ${CONSUL_HTTP_KEY}
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
      CONSUL_WATCH_INTERVAL_SECONDS: ${CONSUL_WATCH_INTERVAL_SECONDS}
    volumes:
      - data_volume:/app/data
volumes:
  data_volume: